2020-12-02 15:23:23,861 INFO    MainThread:22104 [wandb_setup.py:_flush():70] setting env: {}
2020-12-02 15:23:23,861 INFO    MainThread:22104 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2020-12-02 15:23:23,862 INFO    MainThread:22104 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-02 15:23:23,862 INFO    MainThread:22104 [wandb_init.py:_log_setup():303] Logging user logs to D:\2020-2\비즈니스애널리틱스\논문리뷰\Simple-and-Scalable-Predictive-Uncertainty-Estimation-using-Deep-Ensembles\wandb\run-20201202_152323-3y6tgwqp\logs\debug.log
2020-12-02 15:23:23,863 INFO    MainThread:22104 [wandb_init.py:_log_setup():304] Logging internal logs to D:\2020-2\비즈니스애널리틱스\논문리뷰\Simple-and-Scalable-Predictive-Uncertainty-Estimation-using-Deep-Ensembles\wandb\run-20201202_152323-3y6tgwqp\logs\debug-internal.log
2020-12-02 15:23:28,033 INFO    MainThread:22104 [wandb_run.py:_console_start():1218] atexit reg
2020-12-02 15:23:28,034 INFO    MainThread:22104 [wandb_run.py:_redirect():1085] redirect: SettingsConsole.WRAP
2020-12-02 15:23:28,034 INFO    MainThread:22104 [wandb_run.py:_redirect():1116] Wrapping output streams.
2020-12-02 15:23:28,034 INFO    MainThread:22104 [wandb_run.py:_redirect():1132] Redirects installed.
2020-12-02 15:23:28,036 INFO    MainThread:22104 [wandb_run.py:_config_callback():547] config_cb None None {'_wandb': {'cli_version': '0.10.11', 'python_version': '3.7.6', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'learning_rate': 0.1, 'epoch': 300, 'batch_size': 100, 'gpu_device': 0, 'test': 5, 'experiment': 'temp', 'seed': 1}
2020-12-02 15:23:29,240 INFO    MainThread:22104 [wandb_watch.py:watch():35] Watching
2020-12-02 15:23:29,509 INFO    MainThread:22104 [wandb_run.py:_atexit_cleanup():1188] got exitcode: 0
2020-12-02 15:23:29,510 INFO    MainThread:22104 [wandb_run.py:_restore():1160] restore
2020-12-02 15:23:29,514 INFO    MainThread:22104 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "f714ca5bde6c4c288ad07a3452c853fc"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1025
      total_bytes: 1025
    }
  }
}

2020-12-02 15:23:31,515 INFO    MainThread:22104 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "ad13802ccd1c4aba894c89a43a8bf675"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8499
      total_bytes: 8499
    }
  }
}

2020-12-02 15:23:33,521 INFO    MainThread:22104 [wandb_run.py:_wait_for_finish():1305] got exit ret: uuid: "69cb994694b04698bfe43b220a194b37"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 8499
      total_bytes: 8499
    }
  }
}

2020-12-02 15:23:35,026 INFO    MainThread:22104 [wandb_run.py:_show_files():1517] logging synced files
2020-12-02 15:23:35,026 INFO    MainThread:22104 [internal.py:handle_exit():138] Internal process exited
